import { motion } from 'motion/react';
import { AlertTriangle, CheckCircle, Clock, Shield, Wrench } from 'lucide-react';

interface PredictiveMaintenancePanelProps {
  integrity: number;
  corrosion: number;
  pressure: number;
}

export function PredictiveMaintenancePanel({ integrity, corrosion, pressure }: PredictiveMaintenancePanelProps) {
  const getMaintenanceSchedule = () => {
    const schedule = [];
    
    if (corrosion > 0.5) {
      schedule.push({
        task: "Anti-Corrosive Coating Re-application",
        urgency: "High",
        timeframe: "Immediate / Next Docking",
        icon: AlertTriangle,
        color: "text-alert-red",
        bg: "bg-alert-red/10",
        border: "border-alert-red/30"
      });
    } else if (corrosion > 0.2) {
      schedule.push({
        task: "Coating Inspection & Spot Repair",
        urgency: "Medium",
        timeframe: "Within 14 Days",
        icon: Wrench,
        color: "text-warn-orange",
        bg: "bg-warn-orange/10",
        border: "border-warn-orange/30"
      });
    }

    if (integrity < 70) {
      schedule.push({
        task: "Ultrasonic Hull Thickness Measurement",
        urgency: "High",
        timeframe: "Immediate",
        icon: AlertTriangle,
        color: "text-alert-red",
        bg: "bg-alert-red/10",
        border: "border-alert-red/30"
      });
    } else if (integrity < 90) {
      schedule.push({
        task: "Acoustic Emission Monitoring Review",
        urgency: "Low",
        timeframe: "Next Scheduled Maintenance",
        icon: Clock,
        color: "text-cyan-400",
        bg: "bg-cyan-500/10",
        border: "border-cyan-500/30"
      });
    }

    if (pressure > 6.0) {
      schedule.push({
        task: "Pressure Hull Stress Relief Analysis",
        urgency: "Medium",
        timeframe: "Post-Mission",
        icon: Shield,
        color: "text-warn-orange",
        bg: "bg-warn-orange/10",
        border: "border-warn-orange/30"
      });
    }

    if (schedule.length === 0) {
      schedule.push({
        task: "Standard Routine Inspection",
        urgency: "Low",
        timeframe: "90 Days",
        icon: CheckCircle,
        color: "text-safe-green",
        bg: "bg-safe-green/10",
        border: "border-safe-green/30"
      });
    }

    return schedule;
  };

  const schedule = getMaintenanceSchedule();

  return (
    <div className="bg-navy-800 border border-navy-700 rounded-lg p-6 flex flex-col h-full overflow-hidden">
      <div className="flex items-center justify-between mb-6 border-b border-navy-700 pb-4">
        <h3 className="text-lg font-mono text-slate-200 uppercase tracking-widest flex items-center gap-3">
          <Wrench className="w-5 h-5 text-cyan-400" />
          AI Predictive Maintenance Schedule
        </h3>
        <div className="flex items-center gap-2">
          <span className="bg-cyan-500/20 text-cyan-400 border border-cyan-500/50 px-3 py-1 rounded text-xs font-mono font-bold animate-pulse">
            AI MODEL: ACTIVE
          </span>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto pr-2 space-y-4">
        {schedule.map((item, idx) => (
          <motion.div 
            key={idx}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: idx * 0.1 }}
            className={`p-4 rounded-lg border flex items-start gap-4 ${item.bg} ${item.border}`}
          >
            <div className={`p-2 rounded-full bg-navy-900 border ${item.border}`}>
              <item.icon className={`w-6 h-6 ${item.color}`} />
            </div>
            <div className="flex-1">
              <div className="flex items-center justify-between mb-1">
                <h4 className={`font-bold font-mono text-sm uppercase ${item.color}`}>{item.task}</h4>
                <span className={`text-[10px] font-mono font-bold px-2 py-0.5 rounded border uppercase ${item.color} ${item.border}`}>
                  {item.urgency} URGENCY
                </span>
              </div>
              <div className="flex items-center gap-2 text-slate-400 text-xs font-mono mt-2">
                <Clock className="w-3 h-3" />
                <span>RECOMMENDED TIMEFRAME: <strong className="text-slate-200">{item.timeframe}</strong></span>
              </div>
            </div>
          </motion.div>
        ))}
      </div>
      
      <div className="mt-6 pt-4 border-t border-navy-700">
        <p className="text-xs text-slate-500 font-mono leading-relaxed">
          * Recommendations are generated by the VARUNA-DT AI model based on real-time telemetry, historical fatigue data, and galvanic corrosion rates.
        </p>
      </div>
    </div>
  );
}
